//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalisahaOdev.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FieldAppDBEntities : DbContext
    {
        public FieldAppDBEntities()
            : base("name=FieldAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fields> Fields { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Rezervasyon> Rezervasyon { get; set; }
    }
}
